# Generated by Django 2.0 on 2020-03-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderacc', models.CharField(blank=True, max_length=19, null=True, verbose_name='订单编号')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=16, null=True, verbose_name='作者')),
                ('date', models.CharField(blank=True, max_length=14, null=True, verbose_name='提交时间')),
                ('iscode', models.IntegerField(blank=True, default=-2, null=True, verbose_name='状态')),
                ('similarity', models.FloatField(blank=True, default=0, null=True, verbose_name='相似度')),
                ('textnumber', models.IntegerField(default=0, verbose_name='文章字符数')),
                ('taskid', models.CharField(blank=True, max_length=38, verbose_name='taskid')),
                ('filepath', models.CharField(default='', max_length=254, verbose_name='文本路径')),
                ('zipurl', models.URLField(blank=True, null=True, verbose_name='报告压缩包地址')),
            ],
            options={
                'verbose_name': '检测列表',
                'verbose_name_plural': '检测列表',
                'db_table': 'detectionlist',
            },
        ),
        migrations.CreateModel(
            name='ErrotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderacc', models.CharField(blank=True, max_length=16, null=True, verbose_name='订单编号')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=16, null=True, verbose_name='作者')),
                ('date', models.CharField(blank=True, max_length=14, null=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '错误列表',
                'verbose_name_plural': '错误列表',
                'db_table': 'errorlist',
            },
        ),
        migrations.CreateModel(
            name='Globo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('info', models.CharField(max_length=128, verbose_name='信息')),
                ('isActivate', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '全局管理',
                'verbose_name_plural': '全局管理',
                'db_table': 'globo',
            },
        ),
        migrations.CreateModel(
            name='IsActivateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=12, unique=True, verbose_name='卡号')),
                ('isActivate', models.BooleanField(default=False, verbose_name='是否已使用')),
            ],
            options={
                'verbose_name': '检测卡',
                'verbose_name_plural': '检测卡',
                'db_table': 'isactivatecode',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(default='A', max_length=4, verbose_name='订单类型')),
                ('ordernumber', models.CharField(default=0, max_length=20, verbose_name='订单号')),
                ('date', models.CharField(default=0, max_length=16, verbose_name='时间')),
                ('quantity_residual', models.IntegerField(default=0, verbose_name='剩余数量')),
            ],
            options={
                'verbose_name': '订单管理列表',
                'verbose_name_plural': '订单管理列表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Packdocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=128, null=True, verbose_name='文档名称')),
            ],
            options={
                'verbose_name': '打包文档',
                'verbose_name_plural': '打包文档',
                'db_table': 'packdocument',
            },
        ),
        migrations.CreateModel(
            name='Surplus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(blank=True, default=0, verbose_name='A剩余')),
                ('p', models.IntegerField(blank=True, default=0, verbose_name='P剩余')),
                ('v', models.IntegerField(blank=True, default=0, verbose_name='V剩余')),
            ],
            options={
                'verbose_name': '代理充值',
                'verbose_name_plural': '代理充值',
                'db_table': 'surplus',
            },
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=128, null=True, verbose_name='域名')),
                ('individuation', models.CharField(blank=True, max_length=32, null=True, verbose_name='个性化')),
                ('treid', models.CharField(blank=True, max_length=16, null=True, verbose_name='宝贝ID')),
                ('WW', models.CharField(blank=True, max_length=16, null=True, verbose_name='旺旺')),
                ('qq', models.CharField(blank=True, max_length=16, null=True, verbose_name='QQ')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='电话')),
                ('iscode', models.BooleanField(default=True, verbose_name='授权状态')),
                ('date', models.CharField(blank=True, max_length=14, null=True, verbose_name='授权时间')),
                ('operation', models.CharField(blank=True, max_length=12, null=True, verbose_name='操作')),
            ],
            options={
                'verbose_name': '宝贝管理',
                'verbose_name_plural': '宝贝管理',
                'db_table': 'treasure',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=12, unique=True, verbose_name='账户')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('vx', models.CharField(blank=True, max_length=16, null=True, verbose_name='微信号')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='电话')),
                ('qq', models.CharField(blank=True, max_length=16, null=True, verbose_name='QQ号')),
                ('website', models.CharField(blank=True, max_length=64, null=True, verbose_name='网站')),
                ('domain', models.CharField(blank=True, max_length=64, null=True, verbose_name='域名')),
            ],
            options={
                'verbose_name': '代理列表',
                'verbose_name_plural': '代理列表',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='treasure',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='代理商'),
        ),
        migrations.AddField(
            model_name='surplus',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='代理商'),
        ),
        migrations.AddField(
            model_name='packdocument',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='代理商'),
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='代理商'),
        ),
        migrations.AddField(
            model_name='isactivatecode',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='代理商'),
        ),
        migrations.AddField(
            model_name='errotlist',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='代理商'),
        ),
        migrations.AddField(
            model_name='detectionlist',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='代理商'),
        ),
    ]
