# Generated by Django 2.0 on 2020-03-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surplus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(blank=True, default=0, verbose_name='A剩余')),
                ('p', models.IntegerField(blank=True, default=0, verbose_name='P剩余')),
                ('v', models.IntegerField(blank=True, default=0, verbose_name='V剩余')),
            ],
            options={
                'verbose_name': '用户剩余量表',
                'verbose_name_plural': '用户剩余量表',
                'db_table': 'surplus',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(verbose_name='账户')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('vx', models.CharField(blank=True, max_length=16, null=True, verbose_name='微信号')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='电话')),
                ('qq', models.CharField(blank=True, max_length=16, null=True, verbose_name='QQ号')),
                ('website', models.CharField(blank=True, max_length=64, null=True, verbose_name='网站')),
                ('domain', models.CharField(blank=True, max_length=64, null=True, verbose_name='域名')),
            ],
            options={
                'verbose_name': '代理商账户管理表',
                'verbose_name_plural': '代理商账户管理表',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='surplus',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='用户'),
        ),
    ]
