# Generated by Django 2.0 on 2020-03-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(max_length=12, verbose_name='账户'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='电话'),
        ),
    ]
