# Generated by Django 2.0 on 2020-03-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20200301_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='isActivateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=12, verbose_name='卡号')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('isActivate', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '检测卡余量表',
                'verbose_name_plural': '检测卡余量表',
                'db_table': 'isactivatecode',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(max_length=12, unique=True, verbose_name='账户'),
        ),
    ]
