# Generated by Django 2.0 on 2020-03-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20200311_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionlist',
            name='detection_number',
        ),
        migrations.AddField(
            model_name='treasure',
            name='xitong',
            field=models.CharField(choices=[('A', 'A类型,5W字以内'), ('P', 'P类型,15W字以内'), ('V', 'V类型,25W字以内')], default=1, max_length=6, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
