# Generated by Django 2.0 on 2020-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20200301_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isactivatecode',
            name='card',
            field=models.CharField(max_length=12, unique=True, verbose_name='卡号'),
        ),
    ]
