# Generated by Django 2.0 on 2020-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20200312_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlist',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='errotlist',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(default=0, max_length=20, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordernumber',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='授权时间'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='treid',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='宝贝ID'),
        ),
    ]
