# Generated by Django 2.0 on 2020-03-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20200301_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=12, null=True, verbose_name='别名(域名)')),
                ('orderacc', models.CharField(blank=True, max_length=16, null=True, verbose_name='订单编号')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=16, null=True, verbose_name='作者')),
                ('serialnumber', models.CharField(blank=True, max_length=16, null=True, verbose_name='编号规则')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('iscode', models.IntegerField(blank=True, null=True, verbose_name='状态')),
                ('similarity', models.CharField(blank=True, max_length=8, null=True, verbose_name='相似度')),
                ('operation', models.CharField(blank=True, max_length=8, null=True, verbose_name='操作')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '检测列表',
                'verbose_name_plural': '检测列表',
                'db_table': 'detectionlist',
            },
        ),
        migrations.CreateModel(
            name='ErrotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=12, null=True, verbose_name='别名(域名)')),
                ('orderacc', models.CharField(blank=True, max_length=16, null=True, verbose_name='订单编号')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=16, null=True, verbose_name='作者')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '错误列表',
                'verbose_name_plural': '错误列表',
                'db_table': 'errorlist',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderacc', models.CharField(blank=True, max_length=20, null=True, verbose_name='订单号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='时间')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='可用件数')),
                ('operation', models.CharField(blank=True, max_length=8, null=True, verbose_name='操作')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单管理列表',
                'verbose_name_plural': '订单管理列表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=128, null=True, verbose_name='域名')),
                ('individuation', models.CharField(blank=True, max_length=32, null=True, verbose_name='个性化')),
                ('treid', models.CharField(blank=True, max_length=16, null=True, verbose_name='宝贝ID')),
                ('WW', models.CharField(blank=True, max_length=16, null=True, verbose_name='旺旺')),
                ('qq', models.CharField(blank=True, max_length=16, null=True, verbose_name='QQ')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='电话')),
                ('iscode', models.BooleanField(default=True, verbose_name='授权状态')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='授权时间')),
                ('operation', models.CharField(blank=True, max_length=12, null=True, verbose_name='操作')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '宝贝管理',
                'verbose_name_plural': '宝贝管理',
                'db_table': 'treasure',
            },
        ),
        migrations.RemoveField(
            model_name='isactivatecode',
            name='number',
        ),
        migrations.AlterField(
            model_name='isactivatecode',
            name='isActivate',
            field=models.BooleanField(default=True, verbose_name='是否销毁'),
        ),
    ]
