# Generated by Django 2.0 on 2020-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20200312_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlist',
            name='isclear',
            field=models.BooleanField(default=False, verbose_name='用户是否删除'),
        ),
    ]
