# Generated by Django 2.0 on 2020-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20200301_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionlist',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='detectionlist',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='detectionlist',
            name='serialnumber',
        ),
        migrations.RemoveField(
            model_name='errotlist',
            name='domain',
        ),
        migrations.AlterField(
            model_name='detectionlist',
            name='date',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='errotlist',
            name='date',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='date',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='授权时间'),
        ),
    ]
