# Generated by Django 2.0 on 2020-03-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_detectionlist_isclear'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freeze',
            field=models.BooleanField(default=False, verbose_name='是否冻结'),
        ),
    ]
