# Generated by Django 2.0 on 2020-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_order_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlist',
            name='perform_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='完成时间'),
        ),
    ]
