# Generated by Django 2.0 on 2020-03-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20200303_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlist',
            name='taskid',
            field=models.CharField(blank=True, max_length=38, verbose_name='taskid'),
        ),
    ]
