# Generated by Django 2.0 on 2020-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_detectionlist_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlist',
            name='htmlurl',
            field=models.URLField(blank=True, null=True, verbose_name='在线报告地址'),
        ),
        migrations.AddField(
            model_name='detectionlist',
            name='zipurl',
            field=models.URLField(blank=True, null=True, verbose_name='报告压缩包地址'),
        ),
        migrations.AlterField(
            model_name='detectionlist',
            name='iscode',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='detectionlist',
            name='similarity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='相似度'),
        ),
    ]
