# Generated by Django 2.0 on 2020-03-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_detectionlist_perform_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionlist',
            old_name='perform_date',
            new_name='report_date',
        ),
    ]
