# Generated by Django 2.0 on 2020-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20200303_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlist',
            name='textpath',
            field=models.CharField(default='', max_length=254, verbose_name='文本路径'),
        ),
    ]
