# Generated by Django 2.0 on 2020-03-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_detectionlist_textpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionlist',
            old_name='textpath',
            new_name='filepath',
        ),
    ]
