# Generated by Django 2.0 on 2020-03-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_auto_20200308_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderacc',
        ),
        migrations.AddField(
            model_name='order',
            name='filename',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='文档名称'),
        ),
    ]
