# Generated by Django 2.0 on 2020-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_auto_20200309_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlist',
            name='orderacc',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='订单编号'),
        ),
    ]
